# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/odroid/projects/istro_rt2017

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/odroid/projects/istro_rt2017

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/odroid/projects/istro_rt2017/CMakeFiles /home/odroid/projects/istro_rt2017/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/odroid/projects/istro_rt2017/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named istro_rt2017

# Build rule for target.
istro_rt2017: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 istro_rt2017
.PHONY : istro_rt2017

# fast build rule for target.
istro_rt2017/fast:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/build
.PHONY : istro_rt2017/fast

camera.o: camera.cpp.o

.PHONY : camera.o

# target to build an object file
camera.cpp.o:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/camera.cpp.o
.PHONY : camera.cpp.o

camera.i: camera.cpp.i

.PHONY : camera.i

# target to preprocess a source file
camera.cpp.i:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/camera.cpp.i
.PHONY : camera.cpp.i

camera.s: camera.cpp.s

.PHONY : camera.s

# target to generate assembly for a file
camera.cpp.s:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/camera.cpp.s
.PHONY : camera.cpp.s

config.o: config.cpp.o

.PHONY : config.o

# target to build an object file
config.cpp.o:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/config.cpp.o
.PHONY : config.cpp.o

config.i: config.cpp.i

.PHONY : config.i

# target to preprocess a source file
config.cpp.i:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/config.cpp.i
.PHONY : config.cpp.i

config.s: config.cpp.s

.PHONY : config.s

# target to generate assembly for a file
config.cpp.s:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/config.cpp.s
.PHONY : config.cpp.s

ctrlboard.o: ctrlboard.cpp.o

.PHONY : ctrlboard.o

# target to build an object file
ctrlboard.cpp.o:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/ctrlboard.cpp.o
.PHONY : ctrlboard.cpp.o

ctrlboard.i: ctrlboard.cpp.i

.PHONY : ctrlboard.i

# target to preprocess a source file
ctrlboard.cpp.i:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/ctrlboard.cpp.i
.PHONY : ctrlboard.cpp.i

ctrlboard.s: ctrlboard.cpp.s

.PHONY : ctrlboard.s

# target to generate assembly for a file
ctrlboard.cpp.s:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/ctrlboard.cpp.s
.PHONY : ctrlboard.cpp.s

dataset.o: dataset.cpp.o

.PHONY : dataset.o

# target to build an object file
dataset.cpp.o:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/dataset.cpp.o
.PHONY : dataset.cpp.o

dataset.i: dataset.cpp.i

.PHONY : dataset.i

# target to preprocess a source file
dataset.cpp.i:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/dataset.cpp.i
.PHONY : dataset.cpp.i

dataset.s: dataset.cpp.s

.PHONY : dataset.s

# target to generate assembly for a file
dataset.cpp.s:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/dataset.cpp.s
.PHONY : dataset.cpp.s

dmap.o: dmap.cpp.o

.PHONY : dmap.o

# target to build an object file
dmap.cpp.o:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/dmap.cpp.o
.PHONY : dmap.cpp.o

dmap.i: dmap.cpp.i

.PHONY : dmap.i

# target to preprocess a source file
dmap.cpp.i:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/dmap.cpp.i
.PHONY : dmap.cpp.i

dmap.s: dmap.cpp.s

.PHONY : dmap.s

# target to generate assembly for a file
dmap.cpp.s:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/dmap.cpp.s
.PHONY : dmap.cpp.s

geocalc.o: geocalc.cpp.o

.PHONY : geocalc.o

# target to build an object file
geocalc.cpp.o:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/geocalc.cpp.o
.PHONY : geocalc.cpp.o

geocalc.i: geocalc.cpp.i

.PHONY : geocalc.i

# target to preprocess a source file
geocalc.cpp.i:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/geocalc.cpp.i
.PHONY : geocalc.cpp.i

geocalc.s: geocalc.cpp.s

.PHONY : geocalc.s

# target to generate assembly for a file
geocalc.cpp.s:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/geocalc.cpp.s
.PHONY : geocalc.cpp.s

gpsdev.o: gpsdev.cpp.o

.PHONY : gpsdev.o

# target to build an object file
gpsdev.cpp.o:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/gpsdev.cpp.o
.PHONY : gpsdev.cpp.o

gpsdev.i: gpsdev.cpp.i

.PHONY : gpsdev.i

# target to preprocess a source file
gpsdev.cpp.i:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/gpsdev.cpp.i
.PHONY : gpsdev.cpp.i

gpsdev.s: gpsdev.cpp.s

.PHONY : gpsdev.s

# target to generate assembly for a file
gpsdev.cpp.s:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/gpsdev.cpp.s
.PHONY : gpsdev.cpp.s

istro_rt2017.o: istro_rt2017.cpp.o

.PHONY : istro_rt2017.o

# target to build an object file
istro_rt2017.cpp.o:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/istro_rt2017.cpp.o
.PHONY : istro_rt2017.cpp.o

istro_rt2017.i: istro_rt2017.cpp.i

.PHONY : istro_rt2017.i

# target to preprocess a source file
istro_rt2017.cpp.i:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/istro_rt2017.cpp.i
.PHONY : istro_rt2017.cpp.i

istro_rt2017.s: istro_rt2017.cpp.s

.PHONY : istro_rt2017.s

# target to generate assembly for a file
istro_rt2017.cpp.s:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/istro_rt2017.cpp.s
.PHONY : istro_rt2017.cpp.s

lidar.o: lidar.cpp.o

.PHONY : lidar.o

# target to build an object file
lidar.cpp.o:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/lidar.cpp.o
.PHONY : lidar.cpp.o

lidar.i: lidar.cpp.i

.PHONY : lidar.i

# target to preprocess a source file
lidar.cpp.i:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/lidar.cpp.i
.PHONY : lidar.cpp.i

lidar.s: lidar.cpp.s

.PHONY : lidar.s

# target to generate assembly for a file
lidar.cpp.s:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/lidar.cpp.s
.PHONY : lidar.cpp.s

mtime.o: mtime.cpp.o

.PHONY : mtime.o

# target to build an object file
mtime.cpp.o:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/mtime.cpp.o
.PHONY : mtime.cpp.o

mtime.i: mtime.cpp.i

.PHONY : mtime.i

# target to preprocess a source file
mtime.cpp.i:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/mtime.cpp.i
.PHONY : mtime.cpp.i

mtime.s: mtime.cpp.s

.PHONY : mtime.s

# target to generate assembly for a file
mtime.cpp.s:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/mtime.cpp.s
.PHONY : mtime.cpp.s

myahrs.o: myahrs.cpp.o

.PHONY : myahrs.o

# target to build an object file
myahrs.cpp.o:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/myahrs.cpp.o
.PHONY : myahrs.cpp.o

myahrs.i: myahrs.cpp.i

.PHONY : myahrs.i

# target to preprocess a source file
myahrs.cpp.i:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/myahrs.cpp.i
.PHONY : myahrs.cpp.i

myahrs.s: myahrs.cpp.s

.PHONY : myahrs.s

# target to generate assembly for a file
myahrs.cpp.s:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/myahrs.cpp.s
.PHONY : myahrs.cpp.s

navig.o: navig.cpp.o

.PHONY : navig.o

# target to build an object file
navig.cpp.o:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/navig.cpp.o
.PHONY : navig.cpp.o

navig.i: navig.cpp.i

.PHONY : navig.i

# target to preprocess a source file
navig.cpp.i:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/navig.cpp.i
.PHONY : navig.cpp.i

navig.s: navig.cpp.s

.PHONY : navig.s

# target to generate assembly for a file
navig.cpp.s:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/navig.cpp.s
.PHONY : navig.cpp.s

sample.o: sample.cpp.o

.PHONY : sample.o

# target to build an object file
sample.cpp.o:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/sample.cpp.o
.PHONY : sample.cpp.o

sample.i: sample.cpp.i

.PHONY : sample.i

# target to preprocess a source file
sample.cpp.i:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/sample.cpp.i
.PHONY : sample.cpp.i

sample.s: sample.cpp.s

.PHONY : sample.s

# target to generate assembly for a file
sample.cpp.s:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/sample.cpp.s
.PHONY : sample.cpp.s

system.o: system.cpp.o

.PHONY : system.o

# target to build an object file
system.cpp.o:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/system.cpp.o
.PHONY : system.cpp.o

system.i: system.cpp.i

.PHONY : system.i

# target to preprocess a source file
system.cpp.i:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/system.cpp.i
.PHONY : system.cpp.i

system.s: system.cpp.s

.PHONY : system.s

# target to generate assembly for a file
system.cpp.s:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/system.cpp.s
.PHONY : system.cpp.s

threads.o: threads.cpp.o

.PHONY : threads.o

# target to build an object file
threads.cpp.o:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/threads.cpp.o
.PHONY : threads.cpp.o

threads.i: threads.cpp.i

.PHONY : threads.i

# target to preprocess a source file
threads.cpp.i:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/threads.cpp.i
.PHONY : threads.cpp.i

threads.s: threads.cpp.s

.PHONY : threads.s

# target to generate assembly for a file
threads.cpp.s:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/threads.cpp.s
.PHONY : threads.cpp.s

vision.o: vision.cpp.o

.PHONY : vision.o

# target to build an object file
vision.cpp.o:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/vision.cpp.o
.PHONY : vision.cpp.o

vision.i: vision.cpp.i

.PHONY : vision.i

# target to preprocess a source file
vision.cpp.i:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/vision.cpp.i
.PHONY : vision.cpp.i

vision.s: vision.cpp.s

.PHONY : vision.s

# target to generate assembly for a file
vision.cpp.s:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/vision.cpp.s
.PHONY : vision.cpp.s

wmodel.o: wmodel.cpp.o

.PHONY : wmodel.o

# target to build an object file
wmodel.cpp.o:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/wmodel.cpp.o
.PHONY : wmodel.cpp.o

wmodel.i: wmodel.cpp.i

.PHONY : wmodel.i

# target to preprocess a source file
wmodel.cpp.i:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/wmodel.cpp.i
.PHONY : wmodel.cpp.i

wmodel.s: wmodel.cpp.s

.PHONY : wmodel.s

# target to generate assembly for a file
wmodel.cpp.s:
	$(MAKE) -f CMakeFiles/istro_rt2017.dir/build.make CMakeFiles/istro_rt2017.dir/wmodel.cpp.s
.PHONY : wmodel.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... istro_rt2017"
	@echo "... camera.o"
	@echo "... camera.i"
	@echo "... camera.s"
	@echo "... config.o"
	@echo "... config.i"
	@echo "... config.s"
	@echo "... ctrlboard.o"
	@echo "... ctrlboard.i"
	@echo "... ctrlboard.s"
	@echo "... dataset.o"
	@echo "... dataset.i"
	@echo "... dataset.s"
	@echo "... dmap.o"
	@echo "... dmap.i"
	@echo "... dmap.s"
	@echo "... geocalc.o"
	@echo "... geocalc.i"
	@echo "... geocalc.s"
	@echo "... gpsdev.o"
	@echo "... gpsdev.i"
	@echo "... gpsdev.s"
	@echo "... istro_rt2017.o"
	@echo "... istro_rt2017.i"
	@echo "... istro_rt2017.s"
	@echo "... lidar.o"
	@echo "... lidar.i"
	@echo "... lidar.s"
	@echo "... mtime.o"
	@echo "... mtime.i"
	@echo "... mtime.s"
	@echo "... myahrs.o"
	@echo "... myahrs.i"
	@echo "... myahrs.s"
	@echo "... navig.o"
	@echo "... navig.i"
	@echo "... navig.s"
	@echo "... sample.o"
	@echo "... sample.i"
	@echo "... sample.s"
	@echo "... system.o"
	@echo "... system.i"
	@echo "... system.s"
	@echo "... threads.o"
	@echo "... threads.i"
	@echo "... threads.s"
	@echo "... vision.o"
	@echo "... vision.i"
	@echo "... vision.s"
	@echo "... wmodel.o"
	@echo "... wmodel.i"
	@echo "... wmodel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

